# Generated by Django 2.2 on 2022-06-22 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20220608_0443'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='filename',
            field=models.TextField(default='0.jpg'),
        ),
    ]
